site_name: DKPlugins Documentation
site_description:
site_url: http://dkplugins.pretronic.net/

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
  extra_css:
    - stylesheets/bootstrap-grid.min.css
    - stylesheets/style.css
  logo: https://content.pretronic.net/brand/dkplugins-logo.png
  favicon: https://content.pretronic.net/brand/dkplugins-logo.png
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - admonition
  - meta
  - pymdownx.smartsymbols
  - def_list
  - pymdownx.tasklist:
      clickable_checkbox: false
  - toc:
      permalink: true
      toc_depth: 3

plugins:
  - search
  - git-revision-date

extra_css:
  - stylesheets/bootstrap-grid.min.css
  - stylesheets/style.css

edit_uri: https://github.com/dkproject/DKPlugins-Documentation/edit/master/projects/home/docs/
disableRepo: true

nav:
  - DKBans:
      - Introduction: dkbans/index.md
      - Support: dkbans/support.md
      - Defintions: dkbans/defintions.md
      - License: dkbans/license.md
      - FAQ: dkbans/frequently-asked-questions.md
      - Plugin Setup:
          - Installation: dkbans/plugin-setup/installation.md
          - Configuration: dkbans/plugin-setup/configuration.md
          - Migration: dkbans/plugin-setup/migration.md
          - Storage: dkbans/plugin-setup/storage.md
          - Punishment templates: dkbans/plugin-setup/punishment-templates.md
      - Plugin Usage:
          - Commands:
              - Overview: dkbans/plugin-usage/commands/index.md
              - Broadcast: dkbans/plugin-usage/commands/broadcast-commands.md
              - Broadcastgroup: dkbans/plugin-usage/commands/broadcast-group-commands.md
              - Report: dkbans/plugin-usage/commands/report-commands.md
              - History: dkbans/plugin-usage/commands/history-commands.md
              - Player: dkbans/plugin-usage/commands/player-commands.md
              - Punishment: dkbans/plugin-usage/commands/punishment-commands.md
              - Filter: dkbans/plugin-usage/commands/filter-commands.md
              - IP-Address: dkbans/plugin-usage/commands/ip-commands.md
              - Additional: dkbans/plugin-usage/commands/additional-commands.md
          - Placeholders: dkbans/plugin-usage/placeholders.md
          - Broadcast: dkbans/plugin-usage/broadcast.md
          - Filter: dkbans/plugin-usage/filter.md
      - Developer API:
          - Getting Started: dkbans/developer/index.md
  - DKCoins:
      - Introduction: dkcoins/index.md
      - Support: dkcoins/support.md
      - Defintions: dkcoins/defintions.md
      - License: dkcoins/license.md
      - FAQ: dkcoins/frequently-asked-questions.md
      - Plugin Setup:
          - Installation: dkcoins/plugin-setup/installation.md
          - Configuration: dkcoins/plugin-setup/configuration.md
          - Migration: dkcoins/plugin-setup/migration.md
          - Storage: dkcoins/plugin-setup/storage.md
      - Plugin Usage:
          - Commands:
              - Overview: dkcoins/plugin-usage/commands/index.md
              - General Commands: dkcoins/plugin-usage/commands/general-commands.md
              - Bank Commands: dkcoins/plugin-usage/commands/bank-commands.md
              - Bank Member Commands: dkcoins/plugin-usage/commands/bank-member-commands.md
              - Bank Role Commands: dkcoins/plugin-usage/commands/bank-role-commands.md
              - Bank Limit Commands: dkcoins/plugin-usage/commands/bank-limit-commands.md
              - Currency Commands: dkcoins/plugin-usage/commands/currency-commands.md
              - User Bank Command: dkcoins/plugin-usage/commands/user-bank-commands.md
          - Placeholders: dkcoins/plugin-usage/placeholders.md
      - Developer API:
          - Getting Started: dkcoins/developer/index.md
  - DKPerms:
      - Introduction: dkperms/index.md
      - Support: dkperms/support.md
      - Defintions: dkperms/defintions.md
      - License: dkperms/license.md
      - FAQ: dkperms/frequently-asked-questions.md
      - Plugin Setup:
          - Installation: dkperms/plugin-setup/installation.md
          - Migration: dkperms/plugin-setup/migration.md
          - Configuration: dkperms/plugin-setup/configuration.md
          - Storage: dkperms/plugin-setup/storage.md
      - Plugin Usage:
          - Commands:
              - Overview: dkperms/plugin-usage/commands/index.md
              - General Commands: dkperms/plugin-usage/commands/general-commands.md
              - User Commands: dkperms/plugin-usage/commands/user-commands.md
              - Group Commands: dkperms/plugin-usage/commands/group-commands.md
              - Permission Commands: dkperms/plugin-usage/commands/permission-commands.md
              - Parent Commands: dkperms/plugin-usage/commands/parent-commands.md
              - Meta Commands: dkperms/plugin-usage/commands/meta-commands.md
              - Track Commands: dkperms/plugin-usage/commands/track-commands.md
              - Rank Commands: dkperms/plugin-usage/commands/rank-commands.md
          - Placeholders: dkperms/plugin-usage/placeholders.md
      - Developer API:
          - Getting Started: dkperms/developer/index.md
          - DKPerms Scopes: dkperms/developer/scopes.md
          - Permission objects: dkperms/developer/objects.md
          - DKPerms Events: dkperms/developer/events.md
  - DKFriends:
      - Introduction: dkfriends/index.md
      - Support: dkfriends/support.md
      - License: dkfriends/license.md
      - Plugin Setup:
          - Installation: dkfriends/plugin-setup/installation.md
          - Storage: dkfriends/plugin-setup/storage.md
  - DKConnect:
      - Introduction: dkconnect/index.md
      - Support: dkconnect/support.md
      - License: dkconnect/license.md
      - Plugin Setup:
          - Installation: dkconnect/plugin-setup/installation.md
          - Storage: dkconnect/plugin-setup/storage.md
  - DKMotd:
      - Introduction: dkmotd/index.md
      - Support: dkmotd/support.md
      - Defintions: dkmotd/defintions.md
      - License: dkmotd/license.md
      - Plugin Setup:
          - Installation: dkmotd/plugin-setup/installation.md
          - Storage: dkmotd/plugin-setup/storage.md
      - Plugin Usage:
          - Commands:
              - Overview: dkmotd/plugin-usage/commands/index.md
              - Motd Commands: dkmotd/plugin-usage/commands/motd-commands.md
              - Maintenance Commands: dkmotd/plugin-usage/commands/maintenance-commands.md
              - Join message Commands: dkmotd/plugin-usage/commands/joinmessage-commands.md
              - Tablist Commands: dkmotd/plugin-usage/commands/tablist-commands.md
  - DKSupport:
      - Introduction: dksupport/index.md
      - Support: dksupport/support.md
      - License: dksupport/license.md
      - Plugin Setup:
          - Installation: dksupport/plugin-setup/installation.md
          - Storage: dksupport/plugin-setup/storage.md

