site_name: DKPlugins Documentation
site_description:
site_url: http://dkplugins.pretronic.net/

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
  extra_css:
    - stylesheets/bootstrap-grid.min.css
    - stylesheets/style.css
  logo: https://content.pretronic.net/brand/dkplugins-logo.png
  favicon: https://content.pretronic.net/brand/dkplugins-logo.png
  palette:
    scheme: preference
    primary: 'green'
    accent: 'green'

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - admonition
  - meta
  - pymdownx.smartsymbols
  - def_list
  - pymdownx.tasklist:
      clickable_checkbox: false
  - toc:
      permalink: true
      toc_depth: 3

plugins:
  - search
  - git-revision-date

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
  - stylesheets/bootstrap-grid.min.css
  - stylesheets/style.css

edit_uri: https://github.com/dkproject/DKPlugins-Documentation/edit/master/projects/home/docs/
disableRepo: true

nav:
  - Overview: index.md
  - DKPerms:
      - Introduction: dkperms/index.md
      - Support: dkperms/support.md
      - Defintions: dkperms/defintions.md
      - FAQ: dkperms/frequently-asked-questions.md
      - Plugin Setup:
          - Installation: dkperms/plugin-setup/installation.md
      - Plugin Usage:
        - Commands:
          - Overview: dkperms/plugin-usage/commands/index.md
          - General Commands: dkperms/plugin-usage/commands/general-commands.md
          - User Commands: dkperms/plugin-usage/commands/user-commands.md
          - Group Commands: dkperms/plugin-usage/commands/group-commands.md
          - Permission Commands: dkperms/plugin-usage/commands/permission-commands.md
          - Parent Commands: dkperms/plugin-usage/commands/parent-commands.md
          - Meta Commands: dkperms/plugin-usage/commands/meta-commands.md
        - Placeholders: dkperms/plugin-usage/placeholders.md
      - Developer API: dkperms/support.md
