site_name: DKPlugins Documentation
site_description:
site_url: http://dkplugins.pretronic.net/

theme:
  name: material
  #custom_dir: overrides
  features:
    - navigation.tabs
  extra_css:
    - stylesheets/bootstrap-grid.min.css
    - stylesheets/style.css
  logo: https://content.pretronic.net/brand/dkplugins-logo.png
  favicon: https://content.pretronic.net/brand/dkplugins-logo.png
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - admonition
  - meta
  - pymdownx.smartsymbols
  - def_list
  - pymdownx.tasklist:
      clickable_checkbox: false
  - toc:
      permalink: true
      toc_depth: 3

plugins:
  - search
  - git-revision-date

  #extra_css:
  # - stylesheets/bootstrap-grid.min.css
  # - stylesheets/style.css

edit_uri: https://github.com/dkproject/DKPlugins-Documentation/edit/master/projects/home/docs/
disableRepo: true

nav:
  - DKBans:
      - Introduction: dkbans/index.md
      - Support: dkbans/support.md
      - Defintions: dkbans/defintions.md
      - License: dkbans/license.md
      - FAQ: dkbans/frequently-asked-questions.md
      - Plugin Setup:
          - Installation: dkbans/plugin-setup/installation.md
          - Configuration: dkbans/plugin-setup/configuration.md
          - Migration: dkbans/plugin-setup/migration.md
          - Storage: dkbans/plugin-setup/storage.md
      - Plugin Usage:
          - Commands:
              - Overview: dkbans/plugin-usage/commands/index.md
          - Placeholders: dkbans/plugin-usage/placeholders.md
      - Developer API:
          - Getting Started: dkbans/developer/index.md
  - DKCoins:
      - Introduction: dkcoins/index.md
      - Support: dkcoins/support.md
      - Defintions: dkcoins/defintions.md
      - License: dkcoins/license.md
      - FAQ: dkcoins/frequently-asked-questions.md
      - Plugin Setup:
          - Installation: dkcoins/plugin-setup/installation.md
          - Configuration: dkcoins/plugin-setup/configuration.md
          - Migration: dkcoins/plugin-setup/migration.md
          - Storage: dkcoins/plugin-setup/storage.md
      - Plugin Usage:
          - Commands:
              - Overview: dkcoins/plugin-usage/commands/index.md
              - General Commands: dkcoins/plugin-usage/commands/general-commands.md
              - Bank Commands: dkcoins/plugin-usage/commands/bank-commands.md
              - Bank Member Commands: dkcoins/plugin-usage/commands/bank-member-commands.md
              - Bank Role Commands: dkcoins/plugin-usage/commands/bank-role-commands.md
              - Bank Limit Commands: dkcoins/plugin-usage/commands/bank-limit-commands.md
              - Currency Commands: dkcoins/plugin-usage/commands/currency-commands.md
              - User Bank Command: dkcoins/plugin-usage/commands/user-bank-commands.md
          - Placeholders: dkcoins/plugin-usage/placeholders.md
      - Developer API:
          - Getting Started: dkcoins/developer/index.md
  - DKPerms:
      - Introduction: dkperms/index.md
      - Support: dkperms/support.md
      - Defintions: dkperms/defintions.md
      - License: dkperms/license.md
      - FAQ: dkperms/frequently-asked-questions.md
      - Plugin Setup:
          - Installation: dkperms/plugin-setup/installation.md
          - Migration: dkperms/plugin-setup/migration.md
          - Configuration: dkperms/plugin-setup/configuration.md
          - Storage: dkperms/plugin-setup/storage.md
      - Plugin Usage:
          - Commands:
              - Overview: dkperms/plugin-usage/commands/index.md
              - General Commands: dkperms/plugin-usage/commands/general-commands.md
              - User Commands: dkperms/plugin-usage/commands/user-commands.md
              - Group Commands: dkperms/plugin-usage/commands/group-commands.md
              - Permission Commands: dkperms/plugin-usage/commands/permission-commands.md
              - Parent Commands: dkperms/plugin-usage/commands/parent-commands.md
              - Meta Commands: dkperms/plugin-usage/commands/meta-commands.md
              - Track Commands: dkperms/plugin-usage/commands/track-commands.md
              - Rank Commands: dkperms/plugin-usage/commands/rank-commands.md
          - Placeholders: dkperms/plugin-usage/placeholders.md
      - Developer API:
          - Getting Started: dkperms/developer/index.md
